processes:
  cityscapes:
    process: data
    input_name: 
    output_name: 
      - x
      - x_ref
      - y
      - filename
    bs: 16
    num_workers: 4
    tag: cityscapes
    args:
      path: ./data/cityscapes_video
      size: 512
      wh: 2.
      nums: -1
      test_size: 512
  
  encoder:
    process: model
    input_name:
      - x
      - x_ref
    output_name:
      - feature
      - stage1_feature
    ddp: True
    tag: dcfm
    args:
      tag: video_encoder
      backbone: segformerb1
      high_level_ch: 256
      stage1: vit1

    opt: 
      lr: 0.00006
      tag: AdamW
      weight_decay: 0.01
    sch: 
      tag: PolyScheduler
      T_max: 160000
      power: 1.0
      eta_min: 0.
      warm_iter: 1500
      warm_ratio: 0.000001
  
  decoder:
    process: model
    input_name:
      - feature
      - stage1_feature
      - y
    output_name:
      - y_L
      - y_L_hat
      - f_L
      - f_L_hat
      - mf_L
      - mf_U
    ddp: True
    tag: dcfm
    args:
      tag: video_decoder
      num_classes: 19
      head_nums: 1
      head_drop: 0.1
      high_level_ch: 256
      bot_ch: -1
      stage1_ch: 32

    opt: 
      lr: 0.0006 # 10 times for mit
      tag: AdamW
      weight_decay: 0.01
    sch: 
      tag: PolyScheduler
      T_max: 160000
      power: 1.0
      eta_min: 0.
      warm_iter: 1500
      warm_ratio: 0.000001
  
  celoss_I:
    process: metric
    input_name:
      - y_L
      - y
    output_name:
      - loss/CE
    tag: CE
    args:
      ignore_index: 255
    lambda: 1.0

  celoss_B:
    process: metric
    input_name:
      - y_L_hat
      - y
    output_name:
      - loss/CE_B
    tag: CE
    args:
      ignore_index: 255
    lambda: 0.4
  
  Loss_F:
    process: metric
    input_name:
      - f_L
      - f_L_hat
    output_name:
      - loss/f
    tag: MSE
    lambda: 0.0

  Loss_PC:
    process: metric
    input_name:
      - mf_L
      - mf_U
    output_name:
      - loss/PC
    tag: MSE
    lambda: 10
  
  MIOU:
    process: metric
    input_name:
      - y_L
      - y
    output_name:
      - metric/mIoU
    tag: mIoU
    args:
      C: 19
    workplace: 
      - valid
    lambda: 1.0

  MIOU_B:
    process: metric
    input_name:
      - y_L_hat
      - y
    output_name:
      - metric/mIoU_B
    tag: mIoU
    args:
      C: 19
    workplace: 
      - valid
    lambda: 1.0

train:
  seed: 1
  max_iter: 160000
  load_iter: -1
  show_interval: 20
  snapshot_interval: 4000
  valid_interval: 4000